//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTMTicketingv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedTicket
    {

        public int TicketID { get; set; }
        public string EmailID { get; set; }
        public string Origin { get; set; }
        public string Destin { get; set; }
        public double Price { get; set; }
        public System.DateTime PurchasedOn { get; set; }
        public int Quantity { get; set; }
        public string TicketType { get; set; }
    }
}
